### ISSUE TITLE
luarocks install luasocket does not work

### ISSUE THREAD

**Issue by thomas-creel** [justdie386/theinstaller#1]
First, thank you for writing this software, it will make Lua on windows much easier.

```
$ luarocks install luasocket

Installing https://luarocks.org/luasocket-3.1.0-1.src.rock

luasocket 3.1.0-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)

Error: Build error: Failed finding the Lua library. You can use `luarocks config variables.LUA_LIBDIR <path>` to set the correct location.
```

Then when attempting to run 
```
$ luarocks config variables.LUA_LIBDIR C:\devel\theinstaller\lua\lib

Error: Could not read existing config file C:\devel\theinstaller\lua\luarocks\bin\config.lua
```

**Comment by thomas-creel** [comment]
Adding 
```
variables["LUALIB"] = "lua51.dll"
```
to my `theinstaller\lua\luarocks\bin\config.lua`
seemed to fix the LUA_LIBDIR issue (got the fix from here:
https://github.com/luarocks/luarocks/issues/905)

But now I am getting an actual compiler issue
```
C:\devel>luarocks install luasocket
Installing https://luarocks.org/luasocket-3.1.0-1.src.rock

luasocket 3.1.0-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
x86_64-w64-mingw32-gcc.exe /nologo /MD /O2 -c -Fosrc/mime.obj -IC:\devel\theinstaller\lua\include src/mime.c -DLUASOCKET_DEBUG -DNDEBUG -Ic:\windows\system32\include
clang-18: error: no such file or directory: '/nologo'
clang-18: error: no such file or directory: '/MD'
clang-18: error: no such file or directory: '/O2'

Error: Build error: Failed compiling object src/mime.obj
```
I think this is an issue with luasocket so I'll close this. If anyone finds a way to install luasocket using this tool, you should comment below.

**Comment by justdie386** [comment]
Mhm, for the luarocks lLIBDIR, it was indeed because you either didn't properly set it with the correct files inside (either lua51.dll or lua5.1.dll seems to depend on where one gets his luarocks binary from) or because you hadn't set the path properly

For the luasocket not compiling, it seems to be related to the mingw toolchain, because it didn't work on my computer aswell. I did my research and apparently it seems like there's been other issues related to the mingw toolchain and i recommend you open an issue in their github about it.

It does seem to be trying to use the arguments as if it was the cl compiler (the one that comes with visual studio, the sort of "default" on windows) try to install luasocket using luarocks install luasocket CC="clang-cl" clang-cl being clang that is compatible with cl's arguments. Tho im not sure if the installer ships clang-cl, but its worth giving a shot.

**Comment by thomas-creel** [comment]
> Mhm, for the luarocks lLIBDIR, it was indeed because you either didn't properly set it with the correct files inside (either lua51.dll or lua5.1.dll seems to depend on where one gets his luarocks binary from) or because you hadn't set the path properly

I think it actually might be an issue with Luarocks, LIBDIR does not really work for whatever reason. In the issue I linked, you can see a lot of people had issue with it: https://github.com/luarocks/luarocks/issues/905 . So if you want the tool to really work "out of the box, no configuration" then setting `variables["LUALIB"] = "lua51.dll"` in the luarocks config may make sense.

> For the luasocket not compiling, it seems to be related to the mingw toolchain, because it didn't work on my computer aswell. I did my research and apparently it seems like there's been other issues related to the mingw toolchain and i recommend you open an issue in their github about it.

Compiling 32-bit luasocket with mingw seems to work fine, but 64-bit luasocket compilation fails. This is reported in some other issues for luasocket https://github.com/lunarmodules/luasocket/issues/376 . So while the issue is with mingw, luasocket should really provide some custom build parameters for mingw-w64 (like they do for 32bit mingw  so that it at least works on windows.

This post: https://github.com/lunarmodules/luasocket/issues/241#issuecomment-394113063
Seems to say using msys2 worked, but doesnt say if it was 32 bit or 64 bit.

**Comment by justdie386** [comment]
> I think it actually might be an issue with Luarocks, LIBDIR does not really work for whatever reason. In the issue I linked, you can see a lot of people had issue with it: [luarocks/luarocks#905](https://github.com/luarocks/luarocks/issues/905) . So if you want the tool to really work "out of the box, no configuration" then setting `variables["LUALIB"] = "lua51.dll"` in the luarocks config may make sense.
> 
Well, the installer takes care of the LIBDIR already, but it currently does it in a way that only allows one lua install at a time. I've figured out a way to make it work with multiple lua versions and will implement it soon enough.

> Compiling 32-bit luasocket with mingw seems to work fine, but 64-bit luasocket compilation fails. This is reported in some other issues for luasocket [lunarmodules/luasocket#376](https://github.com/lunarmodules/luasocket/issues/376) . So while the issue is with mingw, luasocket should really provide some custom build parameters for mingw-w64 (like they do for 32bit mingw so that it at least works on windows.

Im not much of a C specialist if you ask me, i am learning C/C++, so i just don't know what could cause it to work for 32 bits only, or whatnot.
> This post: [lunarmodules/luasocket#241 (comment)](https://github.com/lunarmodules/luasocket/issues/241#issuecomment-394113063) Seems to say using msys2 worked, but doesnt say if it was 32 bit or 64 bit.

You could try using a 32 bit compiler and setting CC to the compiler, then try to install the package, but once again, i want to point out luasocket is trying to pass CL arguments, because it has hardcoded stuff for windows in its build file. I recommend you try to set CC as clang-cl, or install it somehow, because clang-cl is clang which is CL compatible

**Comment by justdie386** [comment]
> First, thank you for writing this software, it will make Lua on windows much easier.
> 
> ```
> $ luarocks install luasocket
> 
> Installing https://luarocks.org/luasocket-3.1.0-1.src.rock
> 
> luasocket 3.1.0-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
> 
> Error: Build error: Failed finding the Lua library. You can use `luarocks config variables.LUA_LIBDIR <path>` to set the correct location.
> ```
> 
> Then when attempting to run
> 
> ```
> $ luarocks config variables.LUA_LIBDIR C:\devel\theinstaller\lua\lib
> 
> Error: Could not read existing config file C:\devel\theinstaller\lua\luarocks\bin\config.lua
> ```

Oh ok i hadn't understood properly. It seems like it does infact have some issues when using a custom location, i was worried it wouldn't work with custom locations, but didn't bother really testing it myself. I'll look into this aswell during the weekend.

I do want to point out tho that you have to restart your terminal, not reboot, but restart your terminal, for your new env variables, such as LUA_LIBDIR which sets the LIBDIR to go into effect. This *might* be it, unless you already have restarted your terminal and it didn't fix it, either way, please let me know if it did or not.

**Comment by thomas-creel** [comment]
I'll need to try the clang-cl and restarting the terminal this weekend, but I'll report back with my findings

**Comment by justdie386** [comment]
i'll test custom locations later on today (NVM i wasn't sure clang-cl was there but i just checked and it is)

**Comment by thomas-creel** [comment]
> You could try using a 32 bit compiler and setting CC to the compiler, then try to install the package, but once again, i want to point out luasocket is trying to pass CL arguments, because it has hardcoded stuff for windows in its build file. I recommend you try to set CC as clang-cl, or install it somehow, because clang-cl is clang which is CL compatible

Building luasocket with 32 bit compiler already works, but isnt really useful for most people.  64-bit luasocket is required to work with most of the software people are building with lua today.

**Comment by justdie386** [comment]
Ah ok, well then im really not sure, but no matter what, its on luasocket's side, i highly recommend you open an issue about this in their repo.

**Comment by justdie386** [comment]
Just for your information, i just tested the installer with a custom location on my machine, and its worked flawlessly, i think the issue you had might have either been a remnant of some previous attempt to install luarocks, or that you simply didn't properly restart your command prompt when running luarocks for the first time.
